[project]
name = "weather"
version = "0.1.0"
description = "Introduction to MCP Server for Weather API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
